### ISSUE TITLE
unable to decrypt

### ISSUE THREAD

**Issue by sharathyadhav1** [BullyBoo/Encryption#2]
javax.crypto.BadPaddingException: error:1e06b065:Cipher functions:EVP_DecryptFinal_ex:BAD_DECRYPT
08-06 16:49:16.708 10106-10159/ru.bullyboo.encryption W/System.err:     at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
08-06 16:49:16.708 10106-10159/ru.bullyboo.encryption W/System.err:     at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:568)

**Comment by BullyBoo** [comment]
Can you please give me some more information? 
What is the name of a cipher method? 
What kind of padding is it? 
What about the key, message and initialization vector? 

Also it would be cool to get some info about your jdk version.
