### ISSUE TITLE
InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by eresid** [BullyBoo/Encryption#5]
I got next error, when use encryption in Unit tests:

> java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at ru.bullyboo.encoder.methods.AES.encrypt(AES.java:179)
	at ru.bullyboo.encoder.builders.BuilderAES.encryption(BuilderAES.java:97)
	at ru.bullyboo.encoder.builders.BaseBuilder.encrypt(BaseBuilder.java:212)

Code:
```java
public String encrypt(String value) {
    return Encoder.BuilderAES()
          .message(value)
          .method(AES.Method.AES_CBC_PKCS5PADDING)
          .key(BuildConfig.APPLICATION_ID)
          .keySize(AES.Key.SIZE_256)
          .iVector(VECTOR)
          .encrypt();
}

**Comment by BullyBoo** [comment]
show me ur key pls

**Comment by eresid** [comment]
@BullyBoo 
```Java
String KEY = "com.domenname.openmedia.stage"; // key
String VECTOR = "0KHQu9Cw0LLQsCDQo9C60YDQsNGX0L3Rlg=="; // iVector
```
On Android works correct, only for Unit-tests does not work

**Comment by BullyBoo** [comment]
@eresid 
Yes, i don`t know why it`s happened.
i tried to test this with unit tests, but it`s not workng.

You can see, that my lib has not unit tests, but has runtime tests))
You can find them in app/src/main/java/ru/bullyboo/encryption/tests

**Comment by arronli** [comment]
the jre runtime maters,  oracle limit the strength of encryption because america's law
maybe you could refer to this page
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
